android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Aumenta um pouco a heap inicial e limita a máxima para evitar OOM kill
org.gradle.jvmargs=-Xms1g -Xmx2g -XX:MaxMetaspaceSize=512m
